# Generated by Django 3.1.7 on 2021-03-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignados', '0002_auto_20210328_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignado',
            name='tutorLaboral',
        ),
    ]
