# Generated by Django 3.0.5 on 2021-04-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asignado',
            new_name='Cuenta',
        ),
    ]
