# Generated by Django 3.1.7 on 2021-03-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cif', models.CharField(max_length=9, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=5)),
                ('localidad', models.CharField(max_length=50)),
                ('tipoJornada', models.CharField(max_length=15)),
                ('dniResponsable', models.CharField(max_length=9, unique=True)),
                ('nombreResponsable', models.CharField(max_length=50)),
                ('apellidosResponsable', models.CharField(max_length=100)),
                ('dniTutorLaboral', models.CharField(max_length=9, unique=True)),
                ('apellidosTutorLaboral', models.CharField(max_length=100)),
                ('emailTutorLaboral', models.CharField(max_length=100)),
                ('telefonoTutorLaboral', models.CharField(max_length=9)),
            ],
        ),
    ]
