# Generated by Django 3.1.7 on 2021-03-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nombreTutorLaboral',
            field=models.CharField(default='nombretutor', max_length=50),
        ),
    ]
