# Generated by Django 3.1.7 on 2021-03-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_auto_20210324_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fechaNacimiento',
            field=models.DateTimeField(),
        ),
    ]
